//auth
export const LOGIN = 'LOGIN';
export const LOG_OUT = 'LOG_OUT';

//profile
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//wallet
export const WALLET_CREATE = 'WALLET_CREATE';
export const WALLET_SUCCESS = 'WALLET_SUCCESS';
export const WALLET_FAILURE = 'WALLET_FAILURE';

//experience
export const EXPERIENCE_CREATE = 'EXPERIENCE_CREATE';
export const EXPERIENCE_CREATE_SUCCESS = 'EXPERIENCE_CREATE_SUCCESS';
export const EXPERIENCE_CREATE_FAILURE = 'EXPERIENCE_CREATE_FAILURE';

export const EXPERIENCE_TOKEN_EXPIRE = 'EXPERIENCE_TOKEN_EXPIRE';
export const EXPERIENCE_TOKEN_EXPIRE_SUCCESS =
  'EXPERIENCE_TOKEN_EXPIRE_SUCCESS';
export const EXPERIENCE_TOKEN_EXPIRE_FAILURE =
  'EXPERIENCE_TOKEN_EXPIRE_FAILURE';

export const RECEIVE_UPCOMING_EXPERIENCES_REQUEST =
  'RECEIVE_UPCOMING_EXPERIENCES_REQUEST';
export const RECEIVE_UPCOMING_EXPERIENCES_SUCCESS =
  'RECEIVE_UPCOMING_EXPERIENCES_SUCCESS';
export const RECEIVE_UPCOMING_EXPERIENCES_FAILURE =
  'RECEIVE_UPCOMING_EXPERIENCES_FAILURE';

export const RECEIVE_PAST_EXPERIENCES_REQUEST =
  'RECEIVE_PAST_EXPERIENCES_REQUEST';
export const RECEIVE_PAST_EXPERIENCES_SUCCESS =
  'RECEIVE_PAST_EXPERIENCES_SUCCESS';
export const RECEIVE_PAST_EXPERIENCES_FAILURE =
  'RECEIVE_PAST_EXPERIENCES_FAILURE';
