//auth
export const LOGIN = 'LOGIN';
export const LOG_OUT = 'LOG_OUT';

//profile
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//wallet
export const WALLET_CREATE = 'WALLET_CREATE';
export const WALLET_SUCCESS = 'WALLET_SUCCESS';
export const WALLET_FAILURE = 'WALLET_FAILURE';

//experience
export const EXPERIENCE_CREATE = 'EXPERIENCE_CREATE';
export const EXPERIENCE_SUCCESS = 'EXPERIENCE_SUCCESS';
export const EXPERIENCE_FAILURE = 'EXPERIENCE_FAILURE';
